project:
  type: book
  output-dir: docs
  
book:
  title: "ğŸ PySchool"
  author: "Python Chile"
  date: "08/02/2024"
  favicon: "images/pc.png"
  repo-url: "https://github.com/python-chile/PySchool2024"

  chapters:
    - index.qmd
    - part: ğŸš€ Talleres
      chapters:
        - material/talleres/intro.qmd
        - material/talleres/taller_1.qmd
        - material/talleres/taller_2.qmd
        - material/talleres/taller_3.qmd
    - part: ğŸ“œ Anexos
      chapters:
        - material/anexos/cierre_evento.qmd
        - material/anexos/aprendizaje.qmd
        - material/anexos/tecnologia.qmd
        - material/anexos/autoria.qmd
        - material/anexos/colaborar.qmd
index:
  qmd:
lang: es

format:
  html:
    theme: flatly
    number-sections: false
    toc: false
    page-layout: full

filters: 
  - pyodide

sin-enumeracion: true  # Esta lÃ­nea es opcional para indicar que no se desea enumeraciÃ³n
